global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: network-metric-app
    metrics_path: /metrics
    static_configs:
      - targets:
          - metric-app:5000
        labels:
          service: network-monitor-demo

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
